### ISSUE TITLE
Creating new ScriptableObject from the H3VR Code nullifies the associated MonoScript

### ISSUE THREAD

**Issue by Frityet** [nrgill28/MeatKit#11]
If you create any scriptable object from the H3VR Code, the MonoScript is assigned "missing" as default

![image](https://user-images.githubusercontent.com/25426233/129247133-e0a0ec06-66e3-4875-9845-cb54de57213e.png)

With this error in the console

![image](https://user-images.githubusercontent.com/25426233/129247420-ea0ec0a2-4b70-4f6e-b4a4-e5e5769916d8.png)

**Comment by nrgill28** [comment]
I am unable to reproduce this issue. After a clean import of the game assemblies I get no errors or warnings for creating a `SosigConfigTemplate` and putting it into an asset bundle and building works without issues.
![image](https://user-images.githubusercontent.com/22647801/129270297-0ebcb525-c610-48c5-bf71-80906dbd2106.png)
